### ISSUE TITLE
Issue 6 for milestone 3: training the model

### ISSUE THREAD

**Issue by burns2321** [burns2321/BIProjectBeasts#6]
- [x] data splitting
- [ ] bootstrapping
- [ ] cross validation(basic, repeated, or LOOCV)
- [x] model training for either classification,regression, association or clustering(as applicable)
- [ ] model performance comparison using resamples(for classification and regression)
